Optimage/Optimage/Models/ImagesModel.cs
using System.Collections.Generic;

namespace Optimage.Models
{
    public class ImagesModel
    {
        public List<string> Names { get; set; }
    }
}

Optimage/Optimage/Controllers/ImageUploadController.cs
using System.IO;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting.Server;
using Optimage.Models;


namespace Optimage.Controllers
{
    public class ImageUploadController : Controller
    {
        // Setting a variable for control the content root folder of solution
        private readonly IWebHostEnvironment Environment;
        public ImageUploadController(IWebHostEnvironment _environment)
        {
            Environment = _environment;
        }

        // --- Startup action --- //
        /**
            Contains the procedures need to be activated when the project is launched:
            - Auto clearing image directory from files and folders
            - View result is a list of uploaded files (running the project, by default, the result is empty)
        **/
        public IActionResult ImageUpload()
        {
            DirectoryInfo folder = new DirectoryInfo(Path.Combine(this.Environment.ContentRootPath, "Images"));
            AutoClearDirectory(folder);
            return View(GetFiles());
        }
 
        // --- Uploading action --- //
        /**
            Saves image upload directory. If missing, create a folder.
            With using file stream creates file in choosen directory.
            Uploading process it's just copying form file in folder.
            A message of uploading result is displayed below the form and list of files becomes updated.
        **/
        [HttpPost]
        public IActionResult ImageUpload(IFormFile uploadedImage)
        {
            string appPath = Path.Combine(this.Environment.ContentRootPath, "Images");
            if (Directory.Exists(appPath) == false)
            {
                Directory.CreateDirectory(appPath);
            }

            string fileName = Path.GetFileName(uploadedImage.FileName);
            using (FileStream stream = new FileStream(Path.Combine(appPath, fileName), FileMode.Create))
            {
                uploadedImage.CopyTo(stream);
                ViewBag.Message = string.Format($"<b>{fileName}</b> uploaded.<br />");
            }

            return View(GetFiles());
        }

        // --- Auto deleting --- //
        /**
            Create Images folder if it doesn't exist, or check all files and folder
            in directory and delete it.
        **/
        private void AutoClearDirectory(DirectoryInfo folder)
        {
            if (folder.Exists == false)
            {
                Directory.CreateDirectory(Path.Combine(this.Environment.ContentRootPath, "Images"));
            }
            else
            {
                foreach (FileInfo file in folder.EnumerateFiles())
                {
                    if (file.Exists)
                    {
                        file.Delete();
                    }
                }
                foreach (DirectoryInfo directory in folder.EnumerateDirectories())
                {
                    if (directory.Exists)
                    {
                        directory.Delete();
                    }
                }
            }
        }

        // --- List of files --- //
        /** 
            Summary function which looking for files in choosen directory and return the string List. 
            Used to display file names on the page. 
        **/
        private ImagesModel GetFiles()
        {
            DirectoryInfo folder = new DirectoryInfo(Path.Combine(this.Environment.ContentRootPath, "Images"));
            FileInfo[] fileNames = folder.GetFiles("*.*");
            ImagesModel images = new ImagesModel() { Names = new List<string>() };
            
            foreach (var file in fileNames)
            {
                images.Names.Add(file.Name);
            }
            return images;
        }

        // --- Download files --- //
        /** 
            Result is generated for every uploaded file as an action link.
            Return action for file download.
        **/
        public FileResult Download(string ImageName)
        {
            var FileVirtualPath = Path.Combine(this.Environment.ContentRootPath, "Images") + "\\" + ImageName;
            byte[] fileBytes = System.IO.File.ReadAllBytes(FileVirtualPath);
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, Path.GetFileName(FileVirtualPath));
        }
    }
}

Optimage/Optimage/Controllers/OptimageController.cs
using Microsoft.AspNetCore.Mvc;

namespace Optimage.Controllers
{
    public class OptimageController : Controller
    {
        public IActionResult Index()
        {
            return View("Optimage");
        }
    }
}

Optimage/Optimage/Views/ImageUpload/ImageUpload.cshtml
@{
    Layout = null;
}

@using Optimage.Models;
@model ImagesModel;

<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="/css/main.css" />
    <script src="/js/ImageUploadScript.js"></script>
</head>
<body>
    <form id="upload-image-form" method="post" enctype="multipart/form-data" asp-controller="ImageUpload" asp-action="Index">
        <div class="upload-form">
            <div class="upload-form__file">
                <input type="file" name="uploadedImage" onchange="fileSelectedChanged(this)" />
            </div>
            <div class="upload-form__submit">
                <input id="submit-image-button" disabled="disabled" type="submit" value="Upload Image" />
            </div>
            <div class="upload-form__message">
                @Html.Raw(ViewBag.Message)
            </div>
        </div>

        <div class="file-table">
            <table>
                <tr>
                    <th>File Name</th>
                    <th>Link</th>
                </tr>
                @foreach (string imageName in Model.Names)
                {
                    <tr>
                        <td>@imageName </td>
                        <td>@Html.ActionLink("Download", "Download", new { ImageName = @imageName }) </td>
                    </tr>
                }
            </table>
        </div>
    </form>
</body>
</html>

Optimage/Optimage/Views/Optimage/Optimage.cshtml
@{
    Layout = null;
}

<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/css/main.css" />
    </head>
    <body>

    </body>
</html>

Optimage/Optimage/Views/Optimage/OptimageView.cshtml
@{
    Layout = null;
}

<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/css/main.css" />
    </head>
    <body>

    </body>
</html>